#!/bin/bash

#Uncomment if want to take printscreen
#scrot /tmp/lockbackground.png
#convert /tmp/lockbackground.png -clamp 5  /tmp/lockbackground.png

#Comment this out if want to use screenshot
convert ~/.wallpaper.jpg -paint 3  ~/.lockbackground.png

[[ -f ~/Dotfiles/overlay.png ]] && convert ~/.lockbackground.png  ~/Dotfiles/overlay.png -gravity center -composite -matte ~/.lockbackground.png

i3lock -e -f -c 000000 -u -i ~/.lockbackground.png
xset dpms force off

