#!/bin/bash

# My first bash script. It takes a screenshot using scrot and also creates thumbnail which size is 15 % from original
# After screenshot, it uses notify-send to tell user that screenshot has been taken.
# Author: Juho "Qurred" Kuusinen"
scrot $HOME/Pictures/Screenshots/%T_%d_m_%Y.png -z
notify-send -t 1500 "Screenshot taken"
